node:
  cluster: test-cluster
  id: test-id

dynamic_resources:
  cds_config:
    path: ./configs/cds.yaml
  lds_config:
    path: ./configs/lds.yaml

admin:
  access_log_path: ./logs/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 19000
