data_dir = "/home/tony/working/project-collection/vector"

[sources.app]
  type = "file"
  include = [
    # Debug logs
    "/home/tony/working/project-collection/vector/app.log",
  ]
  read_from = "beginning"

[transforms.my_transform_id]
  type = "json_parser"
  inputs = ["app"]
  field = "msg"
  drop_field = false
  drop_invalid = false

[sinks.out]
  inputs = ["my_transform_id"]
  type = "console"
  encoding.codec = "text"



# Run: 
# vector --config ./hello-syslog.toml
